apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
