apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redis-stateful.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.headlessService.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  clusterIP: None
  selector:
    {{- include "redis-stateful.selectorLabels" . | nindent 4 }}
