apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-stateful.name" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redis-stateful.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
