apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-stateful.name" . }}-master
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redis-stateful.labels" . | nindent 4 }}
    role: master
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-stateful.selectorLabels" . | nindent 4 }}
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-stateful.name" . }}-slave
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redis-stateful.labels" . | nindent 4 }}
    role: slave
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-stateful.selectorLabels" . | nindent 4 }}
    role: slave
