apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{ include "api-service.labels" . | nindent 4 }}
spec:
{{ if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{ end }}
  selector:
    matchLabels:
      {{ include "api-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{ with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
    {{ end }}
      labels:
        {{ include "api-service.labels" . | nindent 8 }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      serviceAccountName: default
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - --backend-addr
            - {{ include "api-service.backendAddr" . }}
            - --schedule-addr
            - {{ include "api-service.scheduleAddr" . }}
            - --schedule-type
            - {{ include "api-service.scheduleType" . }}
            - --qps
            - {{ include "api-service.qps" . | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: mcp-proxy
              containerPort: {{ .Values.service.mcpProxyPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: mcp-proxy
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.global.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.global.dns }}
      {{ toYaml . | nindent 6 }}
      {{ end }}
