apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "api-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.mcpProxyPort }}
      targetPort: mcp-proxy
      protocol: TCP
      name: mcp-proxy

  selector:
    {{ include "api-service.selectorLabels" . | nindent 4 }}
