apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{ include "controller.labels" . | nindent 4 }}
spec:
{{ if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{ end }}
  selector:
    matchLabels:
      {{ include "controller.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
    {{ with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
    {{ end }}
      labels:
        {{ include "controller.labels" . | nindent 8 }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      restartPolicy: Always
      serviceAccount: {{ include "controller.serviceAccountName" . }}
      serviceAccountName: {{ include "controller.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          args:
            - --namespace
            - {{ include "controller.sandboxNamespace" . }}
            {{- if .Values.leaderElect }}
            - --leader-elect=true
            {{- else }}
            - --leader-elect=false
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: readiness
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: SERVICE_DOMAIN_SUFFIX
              value: {{ .Values.serviceDomainSuffix | quote }}
            {{- if .Values.docker.enabled }}
            - name: ENGINE_TYPE
              value: "docker"
            - name: DOCKER_HOST
              value: {{ .Values.docker.host | quote }}
            - name: DOCKER_TLS_VERIFY
              value: {{ .Values.docker.tls.verify | quote }}
            {{- if .Values.docker.tls.certPath }}
            - name: DOCKER_CERT_PATH
              value: {{ .Values.docker.tls.certPath | quote }}
            {{- end }}
            - name: DOCKER_NETWORK
              value: {{ .Values.docker.network.defaultNetwork | quote }}
            - name: COMPOSE_ENABLED
              value: {{ .Values.docker.compose.enabled | quote }}
            {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.podTemplates }}
            - name: pod-templates
              mountPath: /etc/aenv/pod-templates
              readOnly: true
          {{- end }}
          {{- if and .Values.docker.enabled (eq .Values.docker.host "unix:///var/run/docker.sock") }}
            - name: docker-socket
              mountPath: /var/run/docker.sock
          {{- end }}
          {{- if and .Values.docker.enabled .Values.docker.tls.verify .Values.docker.tls.certPath }}
            - name: docker-certs
              mountPath: {{ .Values.docker.tls.certPath }}
              readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.podTemplates }}
        - name: pod-templates
          configMap:
            name: {{ include "controller.fullname" . }}-pod-templates
      {{- end }}
      {{- if and .Values.docker.enabled (eq .Values.docker.host "unix:///var/run/docker.sock") }}
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      {{- end }}
      {{- if and .Values.docker.enabled .Values.docker.tls.verify .Values.docker.tls.certPath }}
        - name: docker-certs
          secret:
            secretName: docker-tls-certs
      {{- end }}
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.global.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.global.dns }}
      {{ toYaml . | nindent 6 }}
      {{ end }}
