name: AEnv Images Build and Push

on:
  push:
    branches:
      - add_base_image
  workflow_dispatch:

env:
  REGISTRY: aenvironment

jobs:
  build-aenvironemnt-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata for base
        id: meta_base
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/base
          tags: type=raw,value=latest

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./aenv/builtin-envs/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_base.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
